# Generated by Django 2.0.4 on 2018-04-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20180406_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
