# Generated by Django 2.0.4 on 2018-04-09 07:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=120)),
                ('author_body', ckeditor.fields.RichTextField()),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=35)),
                ('linkedin', models.CharField(max_length=45)),
                ('youtube', models.CharField(max_length=35)),
                ('github', models.CharField(max_length=30)),
                ('google_plus', models.CharField(max_length=50)),
            ],
        ),
    ]
