# Generated by Django 2.0.4 on 2018-04-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_socials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
