# Generated by Django 2.0.4 on 2018-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='github',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='google_plus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='youtube',
            field=models.CharField(max_length=100),
        ),
    ]
