# Generated by Django 2.0.4 on 2018-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20180410_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
