# Generated by Django 2.0.4 on 2018-04-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20180410_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('menu_url', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
