# Generated by Django 2.0.4 on 2018-04-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
