# Generated by Django 2.0.4 on 2018-04-10 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20180410_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generall',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='github',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='google_plus',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='youtube',
        ),
        migrations.AddField(
            model_name='widget',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='general'),
        ),
        migrations.AddField(
            model_name='widget',
            name='menu_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='site_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
