# Generated by Django 2.0.4 on 2018-04-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20180410_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='site_name',
        ),
    ]
